### PR TITLE
Add TimeSpan TypeHandler for Dapper

### LINKED ISSUE #108: Add TimeSpan TypeHandler for Dapper
Dapper does not natively support `TimeSpan`, so it is necessary to create a **Type Handler** that automatically converts this data type to ticks and viceversa.

### PR DESCRIPTION
**Pull request by fabriziobagala**
# Add TimeSpan TypeHandler for Dapper

## 🎯 Purpose
Adds a custom TypeHandler for TimeSpan to improve data type mapping between database and .NET objects when using Dapper.

Closes #108

## 🔍 Changes
- Added `TimeSpanTypeHandler` class that handles TimeSpan serialization/deserialization
- Implements flexible parsing from various data types (string, long, int, double)
- Stores TimeSpan values as ticks (BIGINT) in the database
- Added NET6_0_OR_GREATER conditional compilation to ensure compatibility
- Provides a static Configure() method for easy registration

### CODE REVIEW

**Comment by marcominerva** [comment]
Why did you close the PR?

**Comment by fabriziobagala** [comment]
I closed the PR because I had a doubt whether doing the PR directly from `master` to `master` was within your development flow. If you tell me what your default flow is, I will create a new PR for you in the day. Thank you

**Comment by marcominerva** [comment]
You can just retarget this PR to the `develop` branch.

**Comment by fabriziobagala** [comment]
Yesterday I messed up my branches a bit. Sure enough, my new `master` no longer matches the one reported in this PR. I will recreate everything again.

**Pull request closed without merging**
